export const siteOrigin = 'https://vivien.lv';

export const siteLocales = ['en', 'lv', 'fr', 'ru'];
export const bookingLocales = ['en', 'lv', 'ru'];
export const fallbackLocale = 'en';
export const fallbackBookingLocale = 'en';

export const slugPattern = '[A-Za-z0-9._~-]+';
export const sectionSlugs = ['menu', 'events', 'gallery', 'specials', 'careers', 'contact'];

export const shortLinkGroups = [
  {
    prefix: 'e',
    kind: 'event',
    source: 'shortlink',
    medium: 'event',
    baseCampaign: 'events',
    eventContent: null,
    sectionLinks: true,
  },
  {
    prefix: 'poster',
    kind: 'event',
    source: 'poster',
    medium: 'offline',
    baseCampaign: 'events',
    content: 'qr_code',
    eventContent: 'qr_code',
    sectionLinks: true,
  },
  {
    prefix: 'visam',
    kind: 'event',
    source: 'visam',
    medium: 'partner_app',
    baseCampaign: 'events',
    content: 'mobile_app',
    eventContent: 'mobile_app',
    sectionLinks: true,
  },
  {
    prefix: 'visam-ig',
    kind: 'event',
    source: 'visam',
    medium: 'partner_social',
    baseCampaign: 'events',
    content: 'instagram_blog',
    eventContent: 'instagram_blog',
    sectionLinks: true,
  },
  {
    prefix: 'visam-tt',
    kind: 'event',
    source: 'visam',
    medium: 'partner_social',
    baseCampaign: 'events',
    content: 'tiktok_blog',
    eventContent: 'tiktok_blog',
    sectionLinks: true,
  },
  {
    prefix: 'meta-event',
    kind: 'event',
    source: 'meta',
    medium: 'paid_social',
    baseCampaign: 'events',
    content: 'event_link',
    campaignOverride: true,
    sectionLinks: true,
    localePrefixAliases: true,
  },
  {
    prefix: 'google',
    kind: 'event',
    source: 'google',
    medium: 'cpc',
    baseCampaign: 'google_ads',
    content: 'site_home',
    eventContent: 'event_link',
    campaignOverride: true,
    sectionLinks: true,
    pageLinks: [
      {
        slug: 'gift-card',
        path: 'gift-card',
        campaign: 'page_gift_card',
        content: 'page_gift_card',
      },
    ],
    baseHash: null,
  },
  {
    prefix: 'email',
    kind: 'event',
    source: 'newsletter',
    medium: 'email',
    baseCampaign: 'newsletter',
    content: 'site_home',
    eventContent: 'event_link',
    campaignOverride: true,
    sectionLinks: true,
    pageLinks: [
      {
        slug: 'gift-card',
        path: 'gift-card',
        campaign: 'page_gift_card',
        content: 'page_gift_card',
      },
    ],
    baseHash: null,
  },
  {
    prefix: 'x',
    kind: 'event',
    source: 'twitter',
    medium: 'social',
    baseCampaign: 'bio',
    content: 'profile',
    sectionLinks: true,
    baseHash: 'menu',
  },
  {
    prefix: 'ig',
    kind: 'event',
    source: 'instagram',
    medium: 'social',
    baseCampaign: 'bio',
    content: 'profile',
    sectionLinks: true,
    baseHash: null,
  },
  {
    prefix: 'fb',
    kind: 'event',
    source: 'facebook',
    medium: 'social',
    baseCampaign: 'bio',
    content: 'profile',
    sectionLinks: true,
    baseHash: null,
  },
  {
    prefix: 'tt',
    kind: 'event',
    source: 'tiktok',
    medium: 'social',
    baseCampaign: 'bio',
    content: 'profile',
    sectionLinks: true,
    baseHash: null,
  },
  {
    prefix: 'x-book',
    kind: 'booking',
    source: 'twitter',
    medium: 'social',
    baseCampaign: 'x_launch',
    baseContent: 'pinned_post',
    baseBookingSource: 'x_pinned_post',
    bookingSource: 'x_booking',
  },
  {
    prefix: 'ig-book',
    kind: 'booking',
    source: 'instagram',
    medium: 'social',
    baseCampaign: 'bio',
    baseContent: 'booking',
    baseBookingSource: 'instagram_bio_booking',
    bookingSource: 'instagram_booking',
  },
  {
    prefix: 'fb-book',
    kind: 'booking',
    source: 'facebook',
    medium: 'social',
    baseCampaign: 'page_cta',
    baseContent: 'booking',
    baseBookingSource: 'facebook_page_cta',
    bookingSource: 'facebook_booking',
  },
  {
    prefix: 'fb-organic-book',
    kind: 'booking',
    source: 'facebook',
    medium: 'social',
    baseCampaign: 'organic_post',
    baseContent: 'booking',
    baseBookingSource: 'facebook_organic_booking',
    bookingSource: 'facebook_organic_booking',
  },
  {
    prefix: 'meta-book',
    kind: 'booking',
    source: 'meta',
    medium: 'paid_social',
    baseCampaign: 'booking',
    baseContent: 'booking',
    baseBookingSource: 'meta_booking',
    bookingSource: 'meta_booking',
  },
  {
    prefix: 'google-book',
    kind: 'booking',
    source: 'google',
    medium: 'cpc',
    baseCampaign: 'booking',
    baseContent: 'booking',
    baseBookingSource: 'google_ads_booking',
    bookingSource: 'google_ads_booking',
  },
  {
    prefix: 'email-book',
    kind: 'booking',
    source: 'newsletter',
    medium: 'email',
    baseCampaign: 'booking',
    baseContent: 'booking',
    baseBookingSource: 'email_booking',
    bookingSource: 'email_booking',
  },
  {
    prefix: 'tt-book',
    kind: 'booking',
    source: 'tiktok',
    medium: 'social',
    baseCampaign: 'bio',
    baseContent: 'booking',
    baseBookingSource: 'tiktok_bio_booking',
    bookingSource: 'tiktok_booking',
  },
  {
    prefix: 'ig-lead',
    kind: 'lead',
    source: 'instagram',
    medium: 'paid_social',
    bookingSource: 'instagram_lead_form',
  },
  {
    prefix: 'fb-lead',
    kind: 'lead',
    source: 'facebook',
    medium: 'paid_social',
    bookingSource: 'facebook_lead_form',
  },
  {
    prefix: 'meta-lead',
    kind: 'lead',
    source: 'meta',
    medium: 'paid_social',
    bookingSource: 'meta_lead_form',
  },
  {
    prefix: 'tt-lead',
    kind: 'lead',
    source: 'tiktok',
    medium: 'paid_social',
    bookingSource: 'tiktok_lead_form',
  },
];

export const redirectFixtures = [
  {
    path: '/meta-event/cherry-days/meta_cherry_days_july',
    location: 'https://vivien.lv/en/events/cherry-days/?lang=en&utm_source=meta&utm_medium=paid_social&utm_campaign=meta_cherry_days_july&utm_content=event_link',
  },
  {
    path: '/meta-event/ru/cherry-days/meta_cherry_days_july',
    location: 'https://vivien.lv/ru/events/cherry-days/?lang=ru&utm_source=meta&utm_medium=paid_social&utm_campaign=meta_cherry_days_july&utm_content=event_link',
  },
  {
    path: '/ru/meta-event/cherry-days/meta_cherry_days_july',
    location: 'https://vivien.lv/ru/events/cherry-days/?lang=ru&utm_source=meta&utm_medium=paid_social&utm_campaign=meta_cherry_days_july&utm_content=event_link',
  },
  {
    path: '/lv/meta-event/cherry-days/meta_cherry_days_july',
    location: 'https://vivien.lv/lv/events/cherry-days/?lang=lv&utm_source=meta&utm_medium=paid_social&utm_campaign=meta_cherry_days_july&utm_content=event_link',
  },
  {
    path: '/meta-event/ru/menu/meta_menu_july',
    location: 'https://vivien.lv/ru/?lang=ru&utm_source=meta&utm_medium=paid_social&utm_campaign=meta_menu_july&utm_content=section_menu#menu',
  },
  {
    path: '/google/ru/events/google_cherry_days_july?gclid=test123',
    location: 'https://vivien.lv/ru/?lang=ru&utm_source=google&utm_medium=cpc&utm_campaign=google_cherry_days_july&utm_content=section_events&gclid=test123#events',
  },
  {
    path: '/google/ru/cherry-days/google_cherry_days_july?gbraid=test123',
    location: 'https://vivien.lv/ru/events/cherry-days/?lang=ru&utm_source=google&utm_medium=cpc&utm_campaign=google_cherry_days_july&utm_content=event_link&gbraid=test123',
  },
  {
    path: '/google/en/gift-card/campaign_4_search_riga_core_languages?utm_adgroup=en_restaurant_riga',
    location: 'https://vivien.lv/en/gift-card/?lang=en&utm_source=google&utm_medium=cpc&utm_campaign=campaign_4_search_riga_core_languages&utm_content=page_gift_card&utm_adgroup=en_restaurant_riga',
  },
  {
    path: '/email/ru/menu/july_newsletter?utm_term=summer',
    location: 'https://vivien.lv/ru/?lang=ru&utm_source=newsletter&utm_medium=email&utm_campaign=july_newsletter&utm_content=section_menu&utm_term=summer#menu',
  },
  {
    path: '/email/ru/events/july_newsletter',
    location: 'https://vivien.lv/ru/?lang=ru&utm_source=newsletter&utm_medium=email&utm_campaign=july_newsletter&utm_content=section_events#events',
  },
  {
    path: '/email/ru/gift-card/july_newsletter',
    location: 'https://vivien.lv/ru/gift-card/?lang=ru&utm_source=newsletter&utm_medium=email&utm_campaign=july_newsletter&utm_content=page_gift_card',
  },
  {
    path: '/email-book/ru/july_newsletter',
    location: 'https://vivien.lv/ru/?openBooking=1&lang=ru&booking_source=email_booking&utm_source=newsletter&utm_medium=email&utm_campaign=july_newsletter&utm_content=booking',
  },
  {
    path: '/poster/ru/cherry-days?qr=poster-entrance',
    location: 'https://vivien.lv/ru/events/cherry-days/?lang=ru&utm_source=poster&utm_medium=offline&utm_campaign=event_cherry-days&utm_content=qr_code&qr=poster-entrance',
  },
  {
    path: '/google-book/ru/cherry-days/google_cherry_days_july?wbraid=test123',
    location: 'https://vivien.lv/ru/events/cherry-days/?openBooking=1&lang=ru&booking_source=google_ads_booking&utm_source=google&utm_medium=cpc&utm_campaign=google_cherry_days_july&utm_content=booking&wbraid=test123',
  },
  {
    path: '/ig-book/ru/cherry-days/meta_cherry_days_july?fbclid=test123',
    location: 'https://vivien.lv/ru/events/cherry-days/?openBooking=1&lang=ru&booking_source=instagram_booking&utm_source=instagram&utm_medium=social&utm_campaign=meta_cherry_days_july&utm_content=booking&fbclid=test123',
  },
  {
    path: '/ig/cherry-days',
    location: 'https://vivien.lv/en/events/cherry-days/?lang=en&utm_source=instagram&utm_medium=social&utm_campaign=event_cherry-days&utm_content=event_link',
  },
  {
    path: '/ig/es',
    location: 'https://vivien.lv/en/?lang=en&utm_source=instagram&utm_medium=social&utm_campaign=bio&utm_content=profile',
  },
  {
    path: '/ig/ru/menu',
    location: 'https://vivien.lv/ru/?lang=ru&utm_source=instagram&utm_medium=social&utm_campaign=section_menu&utm_content=section_menu#menu',
  },
  {
    path: '/x/ru/menu/x_menu_july?utm_term=menu_test',
    location: 'https://vivien.lv/ru/?lang=ru&utm_source=twitter&utm_medium=social&utm_campaign=x_menu_july&utm_content=section_menu&utm_term=menu_test#menu',
  },
  {
    path: '/x/ru/cherry-days?utm_term=ignored_by_x',
    location: 'https://vivien.lv/ru/events/cherry-days/?lang=ru&utm_source=twitter&utm_medium=social&utm_campaign=event_cherry-days&utm_content=event_link&utm_term=ignored_by_x',
  },
  {
    path: '/x-book/ru/cherry-days/x_cherry_days_july',
    location: 'https://vivien.lv/ru/events/cherry-days/?openBooking=1&lang=ru&booking_source=x_booking&utm_source=twitter&utm_medium=social&utm_campaign=x_cherry_days_july&utm_content=booking',
  },
];
